# -*- coding: utf-8 -*-
"""Impressora_de_Receitas.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vs-457xwtAyP77toss-kSWTvPBZpyLYN
"""

# https://www.youtube.com/watch?v=Yqrbb1qVWXw
# compilar: https://www.youtube.com/watch?v=aKu-u5fDGjk
import os
import time
import glob
import pathlib

exec = 1

while exec < 2:
  try:
  
    print("")
    print("")
    print("=========================================")
    print("")
    pac = str(input('Entre o nome do paciente: '))
    home = str(pathlib.Path().absolute())
    #home= str(os.getcwd())
    loc = str(home + "\\" + pac) #WINDOWS
    #loc = str(home + "/" + pac) #LINUX
    #loc = str("".\\" + pac)
    os.chdir(loc)
    
    print("")
    print("")
    copias = int(input('Entre o número de cópias de cada receita: '))


    n=0 #capturar número de impressões

    while copias > 0:
      for file in glob.glob('*.pdf'):
        if (file != ''):
          os.startfile (file, 'print')
          print('Imprimindo o arquivo >> ' + str(file))
          n = n + 1
          time.sleep (2) #Sleep for 2 seconds for printing
          copias = copias - 1

    time.sleep (10)
    print("")
    print('O número de páginas impressas foi = ' + str(n))
    print("")

    pac_list = pac.split()
    raiz = os.getcwd()
    raiz_list = raiz.split()
    if (raiz_list [-1] == pac_list [-1]):
      path_parent = os.path.dirname(os.getcwd())
      os.chdir(path_parent)
  
  except Exception as a:
    print(a)
    os.system("pause")

  print("Escolha '1' para reiniciar ou '2' para sair.")
  exec = int(input("Digite '1' ou '2':"))
  pac_list = pac.split()
  raiz = os.getcwd()
  raiz_list = raiz.split()
  if (raiz_list [-1] == pac_list [-1]):
    path_parent = os.path.dirname(os.getcwd())
    os.chdir(path_parent)